export const gameItems = [
  // celtic
  {
    id: "celtic.relic01",
    name: "skean",
    fragments: [0, 1, 2],
    orbs: "Celtic",
  },
  {
    id: "celtic.relic02",
    name: "gae dearg",
    fragments: [0, 1, 2],
    orbs: "Celtic",
  },
  {
    id: "celtic.relic03",
    name: "lorg mor",
    fragments: [0, 1, 2],
    orbs: "Celtic",
  },
  {
    id: "celtic.relic04",
    name: "shillelagh",
    fragments: [0, 1, 2],
    orbs: "Celtic",
  },
  {
    id: "celtic.relic05",
    name: "gae bulg",
    fragments: [0, 1, 2],
    orbs: "Egyptian",
  },
  {
    id: "celtic.relic06",
    name: "conaire mor",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "celtic.relic07",
    name: "cliabh solais",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "celtic.relic08",
    name: "tuagh",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "celtic.relic09",
    name: "fidbac",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "celtic.relic10",
    name: "muirgha",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "celtic.relic11",
    name: "ordus",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "celtic.relic12",
    name: "cruach",
    fragments: [0, 1],
    orbs: "Aether",
  },
  {
    id: "celtic.relic13",
    name: "gae bulg",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "celtic.relic14",
    name: "gae dearg",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "celtic.relic15",
    name: "fuip",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "celtic.relic16",
    name: "samhain",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "celtic.relic17",
    name: "uaithne",
    fragments: [0, 1],
    orbs: "Egyptian",
  },
  {
    id: "celtic.relic18",
    name: "clairseach",
    fragments: [0, 1],
    orbs: "Egyptian",
  },
  {
    id: "celtic.artifact01",
    name: "lamhainn",
    fragments: [0, 1, 2, 3],
    orbs: "Celtic",
  },
  {
    id: "celtic.artifact02",
    name: "slabhra",
    fragments: [0, 1, 2],
    orbs: "Celtic",
  },
  {
    id: "celtic.artifact03",
    name: "safach",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "celtic.artifact04",
    name: "coire ansic",
    fragments: [0, 1, 2],
    orbs: "Aether",
  },
  {
    id: "celtic.artifact05",
    name: "coil",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "celtic.artifact06",
    name: "fealdog",
    fragments: [0],
    orbs: "Celtic",
  },
  {
    id: "celtic.artifact07",
    name: "adharc",
    fragments: [0],
    orbs: "Celtic",
  },
  {
    id: "celtic.artifact08",
    name: "cogar",
    fragments: [0],
    orbs: "Egyptian",
  },
  // egyptian
  {
    id: "egyptian.relic01",
    name: "ankh",
    fragments: [0, 1, 2],
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic02",
    name: "kopesh",
    fragments: [0, 1, 2],
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic03",
    name: "rumh",
    fragments: [0, 1, 2],
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic04",
    name: "was",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "egyptian.relic05",
    name: "harba",
    fragments: [0, 1, 2],
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic06",
    name: "mateh",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "egyptian.relic07",
    name: "djed",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic08",
    name: "heka",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "egyptian.relic09",
    name: "khanarjr",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic10",
    name: "alfatha",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic11",
    name: "hizam",
    fragments: [0, 1],
    orbs: "Aether",
  },
  {
    id: "egyptian.relic12",
    name: "sawlajan",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic13",
    name: "ankh",
    fragments: [0, 1],
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic14",
    name: "kopesh",
    fragments: [0, 1],
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic15",
    name: "al-mawt",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "egyptian.relic16",
    name: "nehasi",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "egyptian.relic17",
    name: "dire",
    fragments: [0, 1],
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic18",
    name: "uraeus",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "egyptian.artifact01",
    name: "saif",
    fragments: [0, 1, 2, 3],
    orbs: "Egyptian",
  },
  {
    id: "egyptian.artifact02",
    name: "fakhkh",
    fragments: [0, 1, 2],
    orbs: "Egyptian",
  },
  {
    id: "egyptian.artifact03",
    name: "sawt",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "egyptian.artifact04",
    name: "tuq",
    fragments: [0, 1, 2],
    orbs: "Aether",
  },
  {
    id: "egyptian.artifact05",
    name: "neq",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "egyptian.artifact06",
    name: "nekhakha",
    fragments: [0],
    orbs: "Greek",
  },
  {
    id: "egyptian.artifact07",
    name: "baydah",
    fragments: [0],
    orbs: "Greek",
  },
  {
    id: "egyptian.artifact08",
    name: "sistrum",
    fragments: [0],
    orbs: "Celtic",
  },
  // greek
  {
    id: "greek.relic01",
    name: "keravnos",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "greek.relic02",
    name: "drepani",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "greek.relic03",
    name: "ravdos",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "greek.relic04",
    name: "bident",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "greek.relic05",
    name: "aegis",
    fragments: [0, 1, 2],
    orbs: "Egyptian",
  },
  {
    id: "greek.relic06",
    name: "trident",
    fragments: [0, 1, 2],
    orbs: "Norse",
  },
  {
    id: "greek.relic07",
    name: "lyre",
    fragments: [0, 1],
    orbs: "Egyptian",
  },
  {
    id: "greek.relic08",
    name: "xiphos",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "greek.relic09",
    name: "flagellum",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "greek.relic10",
    name: "caduceus",
    fragments: [0, 1, 2],
    orbs: "Aether",
  },
  {
    id: "greek.relic11",
    name: "khryselakatos",
    fragments: [0, 1, 2],
    orbs: "Celtic",
  },
  {
    id: "greek.relic12",
    name: "cestus",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "greek.relic13",
    name: "aegis",
    fragments: [0, 1],
    orbs: "Egyptian",
  },
  {
    id: "greek.relic14",
    name: "xiphos",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "greek.relic15",
    name: "chiton",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "greek.relic16",
    name: "skiptro",
    fragments: [0, 1],
    orbs: "Aether",
  },
  {
    id: "greek.relic17",
    name: "oenochoe",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "greek.relic18",
    name: "sfyri",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "greek.artifact01",
    name: "chrysomats",
    fragments: [0, 1, 2, 3],
    orbs: "Greek",
  },
  {
    id: "greek.artifact02",
    name: "alysida",
    fragments: [0, 1, 2],
    orbs: "Greek",
  },
  {
    id: "greek.artifact03",
    name: "labrys",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "greek.artifact04",
    name: "chrysomallon",
    fragments: [0, 1],
    orbs: "Aether",
  },
  {
    id: "greek.artifact05",
    name: "kathreftis",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "greek.artifact06",
    name: "pistolotki",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "greek.artifact07",
    name: "mastigio",
    fragments: [0],
    orbs: "Egyptian",
  },
  {
    id: "greek.artifact08",
    name: "kochyli",
    fragments: [0],
    orbs: "Norse",
  },
  // norse
  {
    id: "norse.relic01",
    name: "gungnir",
    fragments: [0, 1, 2],
    orbs: "Norse",
  },
  {
    id: "norse.relic02",
    name: "stridclub",
    fragments: [0, 1, 2],
    orbs: "Norse",
  },
  {
    id: "norse.relic03",
    name: "mjolnir",
    fragments: [0, 1, 2],
    orbs: "Egyptian",
  },
  {
    id: "norse.relic04",
    name: "laevateinn",
    fragments: [0, 1, 2],
    orbs: "Norse",
  },
  {
    id: "norse.relic05",
    name: "hofud",
    fragments: [0, 1, 2],
    orbs: "Norse",
  },
  {
    id: "norse.relic06",
    name: "svallin vondr",
    fragments: [0, 1, 2],
    orbs: "Aether",
  },
  {
    id: "norse.relic07",
    name: "kona",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "norse.relic08",
    name: "LAEVATEINN",
    fragments: [0, 1],
    orbs: "Aether",
  },
  {
    id: "norse.relic09",
    name: "hammar",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "norse.relic10",
    name: "atgear",
    fragments: [0, 1, 2],
    orbs: "Norse",
  },
  {
    id: "norse.relic11",
    name: "eldrskjold",
    fragments: [0, 1, 2],
    orbs: "Norse",
  },
  {
    id: "norse.relic12",
    name: "skadejarn",
    fragments: [0, 1],
    orbs: "Egyptian",
  },
  {
    id: "norse.relic13",
    name: "GUNGNIR",
    fragments: [0, 1],
    orbs: "Egyptian",
  },
  {
    id: "norse.relic14",
    name: "SVALLIN-VONDR",
    fragments: [0, 1],
    orbs: "Greek",
  },
  {
    id: "norse.relic15",
    name: "hunbogi",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "norse.relic16",
    name: "eikthyrnir",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "norse.relic17",
    name: "skoldr",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "norse.relic18",
    name: "flengja",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "norse.artifact01",
    name: "angurvadal",
    fragments: [0, 1, 2, 3],
    orbs: "Norse",
  },
  {
    id: "norse.artifact02",
    name: "gleipnir",
    fragments: [0, 1, 2],
    orbs: "Norse",
  },
  {
    id: "norse.artifact03",
    name: "taug",
    fragments: [0, 1],
    orbs: "Norse",
  },
  {
    id: "norse.artifact04",
    name: "seidrkista",
    fragments: [0, 1, 2],
    orbs: "Aether",
  },
  {
    id: "norse.artifact05",
    name: "pottr",
    fragments: [0, 1],
    orbs: "Celtic",
  },
  {
    id: "norse.artifact06",
    name: "bjalla",
    fragments: [0],
    orbs: "Cetic",
  },
  {
    id: "norse.artifact07",
    name: "keyra",
    fragments: [0],
    orbs: "Greek",
  },
  {
    id: "norse.artifact08",
    name: "kraviklyra",
    fragments: [0],
    orbs: "Egyptian",
  },
];
